import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { CircleHelp, Handshake, Home, Mail, Star } from "lucide-react";
import { NavDestination, TopNavBar } from "@/components/blocks/top-navbar";

const nunito = Nunito({
	subsets: ["latin"],
});

const navDestinations: NavDestination[] = [
	{
		href: "/about",
		label: "About",
		icon: <Star className="h-6 w-6" />,
	},
	{
		href: "/contact-us",
		label: "Contact Us",
		icon: <Mail className="h-6 w-6" />,
	},
	{
		href: "/home",
		label: "Home",
		icon: <Home className="h-6 w-6" />,
	},
	{
		href: "/join",
		label: "Join Us",
		icon: <Handshake className="h-6 w-6" />,
	},
	{
		href: "/help",
		label: "Help",
		icon: <CircleHelp className="h-6 w-6" />,
	},
];

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${nunito.className} font-sans antialiased`}>
				<TopNavBar destinations={navDestinations} />
				{children}
			</body>
		</html>
	);
}
